{
 "title": "Analog",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "query": {
     "query": "label_values(node_uname_info,job)"
    }
   },
   {
    "name": "analog_job",
    "query": {
     "query": "label_values(substrate_build_info,job)"
    }
   },
   { "name": "interval", "label": "Interval", "query": "30s,1m,2m,3m,5m,10m,30m" }
  ]
 },
 "panels": [
  { "title": "Node Exporter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{job=~\"$job\", mode='system'})"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 4, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - (avg(rate(node_cpu_seconds_total{job=~\"$job\", mode=\"idle\"}[$interval])) * 100)",
     "legendFormat": "CPU Busy"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{job=~\"$job\"} / (node_memory_MemTotal_bytes{job=~\"$job\"})))* 100",
     "legendFormat": "Used RAM Memory"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{job=\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{job=\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"})",
     "legendFormat": "Root FS Used"
    },
    {
     "expr": "scalar(node_load1{job=\"$job\"}) * 100 / count(count(node_cpu_seconds_total{job=\"$job\"}) by (cpu))",
     "legendFormat": "Sys Load"
    }
   ]
  },
  {
   "title": "Disk Space Used Basic(EXT?/XFS)",
   "type": "table",
   "description": "In this kanban: the total disk, usage, available, and usage rate are consistent with the values of the Size, Used, Avail, and Use% columns of the df command, and the value of Use% will be rounded to one decimal place, which will be more accurate .\n\nNote: The Use% algorithm in df is: (size-free) * 100 / (avail + (size-free)), the result is divisible by this value, non-divisible by this value is +1, and the unit of the result is %.\nRefer to the df command source code:",
   "gridPos": { "h": 5, "w": 11, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{job=~'$job',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-0",
     "legendFormat": "总量"
    },
    {
     "expr": "node_filesystem_avail_bytes {job=~'$job',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-0"
    },
    {
     "expr": "(node_filesystem_size_bytes{job=~'$job',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{job=~'$job',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}) *100/(node_filesystem_avail_bytes {job=~'$job',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}+(node_filesystem_size_bytes{job=~'$job',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{job=~'$job',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}))"
    }
   ]
  },
  {
   "title": "Network Traffic Basic",
   "type": "timeseries",
   "description": "Basic network info per interface",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"$job\"}[$__rate_interval])*8",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{job=\"$job\"}[$__rate_interval])*8",
     "legendFormat": "trans {{device}} "
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{job=~\"$job\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(time() - node_boot_time_seconds{job=~\"$job\"})"
    }
   ]
  },
  { "title": "Node Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "node status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "substrate_build_info{job=\"$analog_job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "node name",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "substrate_build_info{job=\"$analog_job\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "node best block height",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "substrate_block_height{status=\"best\", job=\"$analog_job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sync Status Finalized Blocks",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 6, "y": 8 },
   "targets": [
    {
     "expr": "substrate_block_height{status=\"finalized\", job=\"$analog_job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node Traffic",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 13, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(substrate_sub_libp2p_network_bytes_total{direction=\"in\", job=\"$analog_job\"}[$__rate_interval])*8",
     "legendFormat": "Download Bandwith"
    },
    {
     "expr": "irate(substrate_sub_libp2p_network_bytes_total{direction=\"out\", job=\"$analog_job\"}[$__rate_interval])*8",
     "legendFormat": "Upload Bandwith"
    }
   ]
  },
  {
   "title": "chain",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "substrate_build_info{job=\"$analog_job\"}",
     "legendFormat": "{{chain}}"
    }
   ]
  },
  {
   "title": "major sync",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "substrate_sub_libp2p_is_major_syncing{job=\"$analog_job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "node finalized block height",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "substrate_block_height{status=\"finalized\", job=\"$analog_job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "node version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "substrate_build_info{job=\"$analog_job\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(substrate_sub_libp2p_peers_count{job=\"$analog_job\"})"
    }
   ]
  },
  {
   "title": "Peers Discovered",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(substrate_sub_libp2p_peerset_num_discovered{job=\"$analog_job\"})"
    }
   ]
  },
  {
   "title": "chain block height",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "substrate_block_height{status=\"sync_target\", job=\"$analog_job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "rate of tx that finished validation",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "irate(substrate_sub_txpool_validations_finished{chain=\"anlogcc1\", job=\"$analog_job\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "number of tx that finished validation",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 17 },
   "targets": [
    {
     "expr": "substrate_sub_txpool_validations_finished{chain=\"anlogcc1\", job=\"$analog_job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "number of invalid tx",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "substrate_sub_txpool_validations_invalid{chain=\"anlogcc1\", job=\"$analog_job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "rate of invalid tx",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 20 },
   "targets": [
    {
     "expr": "irate(substrate_sub_txpool_validations_invalid{chain=\"anlogcc1\", job=\"$analog_job\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OOM Kills",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_vmstat_oom_kill{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OOM Kills",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 2, "y": 24 },
   "targets": [
    {
     "expr": "node_vmstat_oom_kill{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "node status over time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 6, "y": 24 },
   "targets": [
    {
     "expr": "substrate_build_info{job=\"$analog_job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 19, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "{job=\"analog_testnet_node\"}"
    }
   ]
  }
 ]
}